import { notFound } from "next/navigation"
import EmployeeDetailView from "@/views/Employees/EmployeeDetail"

// This would typically come from a database
const employees = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    mobile: "+91 - 9876543210",
    reportingTo: "Jay Patel",
    status: "Active",
    avatar: "/placeholder.svg?height=100&width=100",
    role: "Senior Developer",
    employeeId: "EMP-001",
    dateOfJoining: "15 Jan 2020",
    department: "Engineering",
    location: "Bangalore",
    gender: "Male",
    dateOfBirth: "12 Apr 1990",
    maritalStatus: "Single",
    bloodGroup: "O+",
    address: "123 Main Street, Bangalore",
    emergencyContacts: [
      {
        name: "Jane Doe",
        email: "jane.doe@example.com",
        relation: "Spouse",
        phone: "+91 - 9876543211",
        address: "123 Main Street, Bangalore",
      },
    ],
    documents: [
      {
        id: "doc1",
        name: "Aadharcard PDF",
        type: "Aadhar Card",
        size: "294kb",
        uploadDate: "15 Jan 2023",
      },
      {
        id: "doc2",
        name: "PAN Card PDF",
        type: "Pan Card",
        size: "156kb",
        uploadDate: "20 Feb 2023",
      },
    ],
    leaveQuota: [
      {
        type: "Casual Leave (CL)",
        total: 12,
        used: 5,
        available: 7,
        overUtilized: 0,
        unused: 7,
      },
      {
        type: "Sick Leave (SL)",
        total: 10,
        used: 3,
        available: 7,
        overUtilized: 0,
        unused: 7,
      },
    ],
    leaves: [
      {
        id: "leave1",
        startDate: "Nov 20, 2024",
        endDate: "Nov 22, 2024",
        type: "CL",
        days: 3,
        appliedOn: "Nov 15, 2024",
        paid: 3,
        unpaid: 0,
        tlStatus: "Approved",
        status: "Approved",
      },
    ],
    assets: [
      {
        id: "asset1",
        name: "MacBook Pro",
        type: "Laptop",
        serialNumber: "MBP2023001",
        assignedDate: "15 Jan 2023",
        condition: "Good",
      },
    ],
    emergencyContact: {
      name: "Jane Doe",
      relation: "Spouse",
      phone: "+91 - 9876543211",
    },
    reportingManager: {
      name: "Jay Patel",
      role: "Engineering Manager",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    team: [
      {
        name: "Rohit Patel",
        role: "Junior Developer",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Arvind Patel",
        role: "Junior Developer",
        avatar: "/placeholder.svg?height=40&width=40",
      },
      {
        name: "Rahul Patel",
        role: "QA Engineer",
        avatar: "/placeholder.svg?height=40&width=40",
      },
    ],
  },
  {
    id: 2,
    name: "Aanand Tiwari",
    email: "aanand.tiwari@example.com",
    mobile: "+91 - 9876543212",
    reportingTo: "Jay Patel",
    status: "Active",
    avatar: "/placeholder.svg?height=100&width=100",
    role: "Product Designer",
    employeeId: "EMP-002",
    dateOfJoining: "05 Mar 2021",
    department: "Design",
    location: "Mumbai",
    gender: "Male",
    dateOfBirth: "23 Jun 1992",
    maritalStatus: "Married",
    bloodGroup: "B+",
    address: "456 Park Avenue, Mumbai",
    emergencyContacts: [
      {
        name: "Priya Tiwari",
        email: "priya.tiwari@example.com",
        relation: "Spouse",
        phone: "+91 - 9876543213",
        address: "456 Park Avenue, Mumbai",
      },
      {
        name: "Raj Tiwari",
        email: "raj.tiwari@example.com",
        relation: "Brother",
        phone: "+91 - 9876543214",
        address: "789 Tech Park, Delhi",
      },
    ],
    documents: [
      {
        id: "doc3",
        name: "Aadharcard PDF",
        type: "Aadhar Card",
        size: "294kb",
        uploadDate: "15 Jan 2023",
      },
      {
        id: "doc4",
        name: "Degree Certificate",
        type: "Education Degree",
        size: "1.2MB",
        uploadDate: "10 Mar 2023",
      },
    ],
    leaveQuota: [
      {
        type: "Casual Leave (CL)",
        total: 12,
        used: 8,
        available: 4,
        overUtilized: 0,
        unused: 4,
      },
      {
        type: "Sick Leave (SL)",
        total: 10,
        used: 2,
        available: 8,
        overUtilized: 0,
        unused: 8,
      },
    ],
    leaves: [
      {
        id: "leave2",
        startDate: "Dec 10, 2024",
        endDate: "Dec 12, 2024",
        type: "CL",
        days: 3,
        appliedOn: "Dec 5, 2024",
        paid: 3,
        unpaid: 0,
        tlStatus: "Pending",
        status: "Pending",
      },
    ],
    assets: [
      {
        id: "asset2",
        name: "iPhone 13",
        type: "Mobile",
        serialNumber: "IP13001",
        assignedDate: "20 Feb 2023",
        condition: "Excellent",
      },
      {
        id: "asset3",
        name: "Dell Monitor",
        type: "Monitor",
        serialNumber: "DM2023001",
        assignedDate: "10 Mar 2023",
        condition: "Good",
      },
    ],
    emergencyContact: {
      name: "Priya Tiwari",
      relation: "Spouse",
      phone: "+91 - 9876543213",
    },
    reportingManager: {
      name: "Jay Patel",
      role: "Design Manager",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    team: [],
  },
  {
    id: 3,
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    mobile: "+91 - 9876543212",
    reportingTo: "Sarah Williams",
    status: "Inactive",
    avatar: "/placeholder.svg?height=100&width=100",
    role: "Backend Developer",
    employeeId: "EMP-003",
    dateOfJoining: "10 Jul 2019",
    department: "Engineering",
    location: "Delhi",
    gender: "Male",
    dateOfBirth: "05 May 1988",
    maritalStatus: "Married",
    bloodGroup: "A+",
    address: "789 Tech Park, Delhi",
    emergencyContacts: [
      {
        name: "Mary Johnson",
        email: "mary.johnson@example.com",
        relation: "Spouse",
        phone: "+91 - 9876543214",
        address: "789 Tech Park, Delhi",
      },
    ],
    documents: [],
    leaveQuota: [],
    leaves: [],
    assets: [],
    emergencyContact: {
      name: "Mary Johnson",
      relation: "Spouse",
      phone: "+91 - 9876543214",
    },
    reportingManager: {
      name: "Sarah Williams",
      role: "Engineering Director",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    team: [],
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily.davis@example.com",
    mobile: "+91 - 9876543213",
    reportingTo: "Jay Patel",
    status: "Active",
    avatar: "/placeholder.svg?height=100&width=100",
    role: "UI Designer",
    employeeId: "EMP-004",
    dateOfJoining: "22 Feb 2022",
    department: "Design",
    location: "Bangalore",
    gender: "Female",
    dateOfBirth: "17 Nov 1994",
    maritalStatus: "Single",
    bloodGroup: "O-",
    address: "321 Designer Avenue, Bangalore",
    emergencyContacts: [],
    documents: [],
    leaveQuota: [],
    leaves: [],
    assets: [],
    emergencyContact: {
      name: "David Davis",
      relation: "Father",
      phone: "+91 - 9876543215",
    },
    reportingManager: {
      name: "Jay Patel",
      role: "Design Manager",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    team: [],
  },
  {
    id: 5,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    mobile: "+91 - 9876543214",
    reportingTo: "Sarah Williams",
    status: "Active",
    avatar: "/placeholder.svg?height=100&width=100",
    role: "DevOps Engineer",
    employeeId: "EMP-005",
    dateOfJoining: "03 Apr 2020",
    department: "Engineering",
    location: "Hyderabad",
    gender: "Male",
    dateOfBirth: "29 Aug 1991",
    maritalStatus: "Single",
    bloodGroup: "AB+",
    address: "456 Cloud Street, Hyderabad",
    emergencyContacts: [],
    documents: [],
    leaveQuota: [],
    leaves: [],
    assets: [],
    emergencyContact: {
      name: "Jennifer Brown",
      relation: "Sister",
      phone: "+91 - 9876543216",
    },
    reportingManager: {
      name: "Sarah Williams",
      role: "Engineering Director",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    team: [],
  },
  {
    id: 6,
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    mobile: "+91 - 9876543215",
    reportingTo: "Jay Patel",
    status: "Inactive",
    avatar: "/placeholder.svg?height=100&width=100",
    role: "QA Engineer",
    employeeId: "EMP-006",
    dateOfJoining: "15 Sep 2021",
    department: "Quality Assurance",
    location: "Pune",
    gender: "Female",
    dateOfBirth: "12 Dec 1993",
    maritalStatus: "Married",
    bloodGroup: "B-",
    address: "789 Testing Road, Pune",
    emergencyContacts: [],
    documents: [],
    leaveQuota: [],
    leaves: [],
    assets: [],
    emergencyContact: {
      name: "James Wilson",
      relation: "Spouse",
      phone: "+91 - 9876543217",
    },
    reportingManager: {
      name: "Jay Patel",
      role: "QA Manager",
      avatar: "/placeholder.svg?height=40&width=40",
    },
    team: [],
  },
]

export default function EmployeeDetailPage({ params }: { params: { id: string } }) {
  // Convert the ID to a number and find the employee
  const employeeId = Number.parseInt(params.id)
  const employee = employees.find((emp) => emp.id === employeeId)

  // If employee not found, show 404 page
  if (!employee) {
    notFound()
  }

  return <EmployeeDetailView employee={employee} />
}

